include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    strict_raw_type: ignore
    avoid_catches_without_on_clauses: ignore

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
